### ISSUE TITLE
Excuse me, is there any problem with this EFI

### ISSUE THREAD

**Issue by ZSS980909** [keyuxing/ROG-B460I-Hackintosh#1]

**Comment by keyuxing** [comment]
It works good on my Hackintosh. No problem has been found.

**Comment by ZSS980909** [comment]
wonderful

**Comment by ZSS980909** [comment]
But my WiFi and Bluetooth don't work

**Comment by keyuxing** [comment]
I use a driver-free WiFi module, so this EFI does't contain any driver for WiFi and Bluetooth. Which WiFi module do you use?

**Comment by ZSS980909** [comment]
才发现你也是中国人 哈哈哈哈 我设备跟你完全一样 就是cpu是10500 wifi用的是dw1560

**Comment by keyuxing** [comment]
哈哈哈哈 DW1560是不免驱的 得打一下驱动 可以参考[这里](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#wifi-and-bluetooth)
