### ISSUE TITLE
大神你好

### ISSUE THREAD

**Issue by IuuuIIIuuu** [keyuxing/ROG-B460I-Hackintosh#2]
HELOO，我跟你的配置差不多的 10400+微星B460迫击炮+6600，可是进入系统就黑屏，还有这么进WINDOS系统呢（双硬盘双系统），可以留个联系方式请教下吗

**Comment by keyuxing** [comment]
我是用的核显，没有独显，黑屏可能和这一点有关系。可以试试先拔掉独显然后插主板上的DP口看能不能进系统。
另外，我们用的主板也不一样。建议先尝试使用相同主板的EFI。Github或者远景上都有不少和你相同配置的EFI。
关于双系统，我个人用的单硬盘双系统，不太了解双硬盘双系统怎么装。你可以参考[OpenCore的官方教程](https://dortania.github.io/OpenCore-Multiboot/empty/diffdisk.html)。

**Comment by IuuuIIIuuu** [comment]
Sor,我看错了，我以为你是另外一个跟我相同主板的人。谢谢你的回答，我继续找找。
